import { dir } from 'i18next';
import type { Metadata } from 'next';
import { languages } from '../i18n/configuration/settings';
import { ReactNode } from 'react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return languages.map((lang) => ({ lang }));
}

interface Props {
	children: ReactNode;
	params: { lang: string };
}

export default function RootLayout({ children, params }: Props) {
	const { lang } = params;
	return (
		<html lang={lang} dir={dir(lang)}>
			<body>{children}</body>
		</html>
	);
}
